
apiVersion: v1
kind: Service
metadata:
  name: demochat-service
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 8080 
    - protocol: TCP
      port: 5222 
      targetPort: 5222 
